name: hideNearbyPlayers
version: '${version}'
main: io.github.pheontern.hidenearbyplugin.HideNearbyPlugin
api-version: '1.20'
authors: [Pheontern]
description: Hide nearby players to prevent them from being in your face.
website: io.github.Pheontern
