name: hideNearbyPlayers
version: '${version}'
main: io.github.pheontern.hidenearbyplugin.HideNearbyPlugin
api-version: '1.20'
authors: [Pheontern]
description: Hide nearby players to prevent them from blocking your view.
website: io.github.Pheontern
commands:
  toggleHide:
    description: Hides nearby players.
    usage: /<command>
  hideDistance:
    description: Changes the distance below which players are hidden for the player that executed the command.
    usage: /<command> decimalValue
  hideStandardDistance:
    description: Changes the standard hide distance that is used when a player hasn't specified their own.
    usage: /<command> decimalValue
  hideVerticalDistance:
    description: Changes the vertical hide distance. This is the same for every player.
    usage: /<command> decimalValue
  hideTickDelay:
    description: Changes the tick-delay between each check for distance between players. Only updated at restart.
    usage: /<command> integerValue
