name: hideNearbyPlayers
version: '${version}'
main: io.github.pheontern.hidenearbyplugin.HideNearbyPlugin
api-version: '1.20'
authors: [Pheontern]
description: Hide nearby players to prevent them from blocking your view.
website: io.github.Pheontern
commands:
  toggleHide:
    description: Hides nearby players.
    usage: /<command>
  hideDistance:
    description: If player is op, changes the distance below which players are hidden.
    usage: /<command> decimalValue
